function PlayerVariables()
{
	StickToConvex		 isVar;
	Acc					 isVar;
	Dec					 isVar;
	Frc					 isVar;
	RollFrc				 isVar;
	AirAcc				 isVar;
	RollDec				 isVar;
	Jump				 isVar;
	JumpMin				 isVar;
	Grv					 isVar;
	TopAcc				 isVar;
	State				 isVar;
	MovementLock		 isVar;
	Rolling				 isVar;
	Jumping				 isVar;
	Pushing              isVar;
	Grounded			 isVar;
	OnObject			 isVar;
	Layer				 isVar;
	Facing				 isVar;
	Hurt			     isVar;
	Death				 isVar;
	Drown				 isVar;
	CharacterID			 isVar;
	PosX				 isVar;
	PosY				 isVar;
	Xsp					 isVar;
	Ysp					 isVar;
	Inertia				 isVar;
	SlopeGravity		 isVar;
	Angle				 isVar;
	VisualAngle			 isVar;
	PeeloutRev			 isVar;
	SpindashRev		     isVar;
	DropdashRev			 isVar;
	DropdashDirection	 isVar;
	SuperState			 isVar;
	SuperStateValue		 isVar;
	SuperStateStar		 isVar;
	IsInvincible		 isVar;
	IsUnderwater		 isVar;
	BarrierType			 isVar;
	BarrierIsActive	     isVar;
	FlyingState			 isVar;
	FlyingTimer			 isVar;
	GlidingState		 isVar;
	GlidingValue		 isVar;
	GlidingDirection     isVar;
	ClimbState		     isVar;
	ClimbValue           isVar;
	ClimbSpeed		 isVar;
	Skidding			 isVar;
	Balancing			 = 0;
	HighSpeedBonus		 isVar;
	InvincibilityBonus   isVar;
	Animation			 isVar;
	yRadius				 isVar;
	xRadius				 isVar;
	yRadiusDefault       isVar;
	xRadiusDefault		 isVar;
	yRadiusRoll			 isVar;
	xRadiusRoll			 isVar;	
	AllowCollision		 isVar;
	Score				 isVar;
	Rings				 isVar;
	Lives				 isVar;
	LivesRewards		 isVar;
	Conts				 isVar;
	Emeralds			 isVar;
	SkiddingTimer		 isVar;
	DebugMode            isVar;
	DebugItem			 isVar;
	DebugSpeed			 isVar;
	ForcedRoll			 isVar;
	ScoreCombo			 isVar;
	
	GlideAcc       = 0;
	GlideSlide     = 0;
	GlideState     = 0;
	GlideValue	   = 0;
	GlideSpeed     = 0;
	GlideDirection = 0;
	GlideFrame	   = 0;
	
	FlightState = 0;
	FlightValue = 0;
	
	AirTimer			 isReal;
	
	RecordedPosX		 isArr;
	RecordedPosY         isArr;
}